#!/usr/bin/env python

__doc__="""

  pliu 20150510

  run pRSEM to calculate priors and use them for abundance estimation
"""

import ChIPSeqExperiment
import Param


def main():
  argdict = getCommandLineArguments()

  param = Param.initFromCommandLineArguments(argdict)
  chipseqexp = ChIPSeqExperiment.initFromParam(param)

  chipseqexp.getFastqEncoding()
  chipseqexp.alignReadByBowtie()


def getCommandLineArguments():
  import argparse

  parser = argparse.ArgumentParser()
  parser.add_argument('--num-threads', type=int)
  parser.add_argument('--chipseq-target-read-files')
  parser.add_argument('--chipseq-control-read-files')
  parser.add_argument('--bowtie-bin-for-chipseq')
  parser.add_argument('--samtools-bin')
  parser.add_argument('--bedtools-bin-for-chipseq')
  parser.add_argument('--quiet', action='store_true')

  ## need to be in the same order as feed in argument
  parser.add_argument('ref_name')
  parser.add_argument('sample_name')
  parser.add_argument('stat_name')
  parser.add_argument('imd_name')
  argdict = vars(parser.parse_args())

  return argdict


if __name__=='__main__':
  main()
